import type { GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { S3Client, ListObjectsCommand } from "@aws-sdk/client-s3";

import styles from "../styles/Home.module.css";
import { getS3ObjectUrl } from "../utils/awsS3Utils";

export async function getStaticProps(context: GetStaticPropsContext) {
  const client = new S3Client({ region: "us-west-2" });

  const data = await client.send(
    new ListObjectsCommand({ Bucket: "artificia.io" })
  );

  const filteredObjects =
    data.Contents?.filter(
      (object) => object.Key !== null && /\.(jpg|png)$/.test(object.Key ?? "")
    ) ?? [];

  const objectUrls = filteredObjects.map((content) =>
    getS3ObjectUrl({
      region: "us-west-2",
      bucket: "artificia.io",
      key: content.Key!,
    })
  );

  return {
    props: {
      assets: objectUrls,
    }, // will be passed to the page component as props
  };
}

const Home: NextPage<{
  assets: string[];
}> = ({ assets }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Artificia.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {assets.map((asset, index) => (
          <Image key={index} src={asset} alt="todo" height="400" width="400" />
        ))}
      </main>
    </div>
  );
};

export default Home;
